name = "sundae-labs/walking-skeleton"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'sundae-labs/walking-skeleton'"

[repository]
user = "sundae-labs"
project = "walking-skeleton"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
